// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brand.proto

package org.schemata.schema;

public final class BrandBuilder {
  private BrandBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.schemata.schema.Brand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool is_active = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The isActive.
     */
    boolean getIsActive();
  }
  /**
   * Protobuf type {@code org.schemata.schema.Brand}
   */
  public static final class Brand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.schemata.schema.Brand)
      BrandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Brand.newBuilder() to construct.
    private Brand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Brand() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Brand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Brand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              isActive_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_Brand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_Brand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.schemata.schema.BrandBuilder.Brand.class, org.schemata.schema.BrandBuilder.Brand.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_ACTIVE_FIELD_NUMBER = 3;
    private boolean isActive_;
    /**
     * <code>bool is_active = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (isActive_ != false) {
        output.writeBool(3, isActive_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isActive_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.schemata.schema.BrandBuilder.Brand)) {
        return super.equals(obj);
      }
      org.schemata.schema.BrandBuilder.Brand other = (org.schemata.schema.BrandBuilder.Brand) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getIsActive()
          != other.getIsActive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IS_ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.Brand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.schemata.schema.BrandBuilder.Brand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.schemata.schema.Brand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.schemata.schema.Brand)
        org.schemata.schema.BrandBuilder.BrandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_Brand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_Brand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.schemata.schema.BrandBuilder.Brand.class, org.schemata.schema.BrandBuilder.Brand.Builder.class);
      }

      // Construct using org.schemata.schema.BrandBuilder.Brand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        isActive_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_Brand_descriptor;
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.Brand getDefaultInstanceForType() {
        return org.schemata.schema.BrandBuilder.Brand.getDefaultInstance();
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.Brand build() {
        org.schemata.schema.BrandBuilder.Brand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.Brand buildPartial() {
        org.schemata.schema.BrandBuilder.Brand result = new org.schemata.schema.BrandBuilder.Brand(this);
        result.id_ = id_;
        result.name_ = name_;
        result.isActive_ = isActive_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.schemata.schema.BrandBuilder.Brand) {
          return mergeFrom((org.schemata.schema.BrandBuilder.Brand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.schemata.schema.BrandBuilder.Brand other) {
        if (other == org.schemata.schema.BrandBuilder.Brand.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.schemata.schema.BrandBuilder.Brand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.schemata.schema.BrandBuilder.Brand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool is_active = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool is_active = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_active = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        
        isActive_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.schemata.schema.Brand)
    }

    // @@protoc_insertion_point(class_scope:org.schemata.schema.Brand)
    private static final org.schemata.schema.BrandBuilder.Brand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.schemata.schema.BrandBuilder.Brand();
    }

    public static org.schemata.schema.BrandBuilder.Brand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Brand>
        PARSER = new com.google.protobuf.AbstractParser<Brand>() {
      @java.lang.Override
      public Brand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Brand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Brand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Brand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.schemata.schema.BrandBuilder.Brand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BrandEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.schemata.schema.BrandEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the previousBrandState field is set.
     */
    boolean hasPreviousBrandState();
    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The previousBrandState.
     */
    org.schemata.schema.BrandBuilder.Brand getPreviousBrandState();
    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    org.schemata.schema.BrandBuilder.BrandOrBuilder getPreviousBrandStateOrBuilder();

    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the currentBrandState field is set.
     */
    boolean hasCurrentBrandState();
    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The currentBrandState.
     */
    org.schemata.schema.BrandBuilder.Brand getCurrentBrandState();
    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    org.schemata.schema.BrandBuilder.BrandOrBuilder getCurrentBrandStateOrBuilder();

    /**
     * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The enum numeric value on the wire for activityType.
     */
    int getActivityTypeValue();
    /**
     * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The activityType.
     */
    org.schemata.schema.SchemataBuilder.ActivityType getActivityType();
  }
  /**
   * Protobuf type {@code org.schemata.schema.BrandEvent}
   */
  public static final class BrandEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.schemata.schema.BrandEvent)
      BrandEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BrandEvent.newBuilder() to construct.
    private BrandEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BrandEvent() {
      activityType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BrandEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BrandEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.schemata.schema.BrandBuilder.Brand.Builder subBuilder = null;
              if (previousBrandState_ != null) {
                subBuilder = previousBrandState_.toBuilder();
              }
              previousBrandState_ = input.readMessage(org.schemata.schema.BrandBuilder.Brand.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(previousBrandState_);
                previousBrandState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.schemata.schema.BrandBuilder.Brand.Builder subBuilder = null;
              if (currentBrandState_ != null) {
                subBuilder = currentBrandState_.toBuilder();
              }
              currentBrandState_ = input.readMessage(org.schemata.schema.BrandBuilder.Brand.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(currentBrandState_);
                currentBrandState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              activityType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_BrandEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_BrandEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.schemata.schema.BrandBuilder.BrandEvent.class, org.schemata.schema.BrandBuilder.BrandEvent.Builder.class);
    }

    public static final int PREVIOUS_BRAND_STATE_FIELD_NUMBER = 1;
    private org.schemata.schema.BrandBuilder.Brand previousBrandState_;
    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the previousBrandState field is set.
     */
    @java.lang.Override
    public boolean hasPreviousBrandState() {
      return previousBrandState_ != null;
    }
    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The previousBrandState.
     */
    @java.lang.Override
    public org.schemata.schema.BrandBuilder.Brand getPreviousBrandState() {
      return previousBrandState_ == null ? org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : previousBrandState_;
    }
    /**
     * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    @java.lang.Override
    public org.schemata.schema.BrandBuilder.BrandOrBuilder getPreviousBrandStateOrBuilder() {
      return getPreviousBrandState();
    }

    public static final int CURRENT_BRAND_STATE_FIELD_NUMBER = 2;
    private org.schemata.schema.BrandBuilder.Brand currentBrandState_;
    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the currentBrandState field is set.
     */
    @java.lang.Override
    public boolean hasCurrentBrandState() {
      return currentBrandState_ != null;
    }
    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The currentBrandState.
     */
    @java.lang.Override
    public org.schemata.schema.BrandBuilder.Brand getCurrentBrandState() {
      return currentBrandState_ == null ? org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : currentBrandState_;
    }
    /**
     * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    @java.lang.Override
    public org.schemata.schema.BrandBuilder.BrandOrBuilder getCurrentBrandStateOrBuilder() {
      return getCurrentBrandState();
    }

    public static final int ACTIVITY_TYPE_FIELD_NUMBER = 3;
    private int activityType_;
    /**
     * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The enum numeric value on the wire for activityType.
     */
    @java.lang.Override public int getActivityTypeValue() {
      return activityType_;
    }
    /**
     * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The activityType.
     */
    @java.lang.Override public org.schemata.schema.SchemataBuilder.ActivityType getActivityType() {
      @SuppressWarnings("deprecation")
      org.schemata.schema.SchemataBuilder.ActivityType result = org.schemata.schema.SchemataBuilder.ActivityType.valueOf(activityType_);
      return result == null ? org.schemata.schema.SchemataBuilder.ActivityType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (previousBrandState_ != null) {
        output.writeMessage(1, getPreviousBrandState());
      }
      if (currentBrandState_ != null) {
        output.writeMessage(2, getCurrentBrandState());
      }
      if (activityType_ != org.schemata.schema.SchemataBuilder.ActivityType.CREATED.getNumber()) {
        output.writeEnum(3, activityType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (previousBrandState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPreviousBrandState());
      }
      if (currentBrandState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurrentBrandState());
      }
      if (activityType_ != org.schemata.schema.SchemataBuilder.ActivityType.CREATED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, activityType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.schemata.schema.BrandBuilder.BrandEvent)) {
        return super.equals(obj);
      }
      org.schemata.schema.BrandBuilder.BrandEvent other = (org.schemata.schema.BrandBuilder.BrandEvent) obj;

      if (hasPreviousBrandState() != other.hasPreviousBrandState()) return false;
      if (hasPreviousBrandState()) {
        if (!getPreviousBrandState()
            .equals(other.getPreviousBrandState())) return false;
      }
      if (hasCurrentBrandState() != other.hasCurrentBrandState()) return false;
      if (hasCurrentBrandState()) {
        if (!getCurrentBrandState()
            .equals(other.getCurrentBrandState())) return false;
      }
      if (activityType_ != other.activityType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPreviousBrandState()) {
        hash = (37 * hash) + PREVIOUS_BRAND_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getPreviousBrandState().hashCode();
      }
      if (hasCurrentBrandState()) {
        hash = (37 * hash) + CURRENT_BRAND_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentBrandState().hashCode();
      }
      hash = (37 * hash) + ACTIVITY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + activityType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.BrandBuilder.BrandEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.schemata.schema.BrandBuilder.BrandEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.schemata.schema.BrandEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.schemata.schema.BrandEvent)
        org.schemata.schema.BrandBuilder.BrandEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_BrandEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_BrandEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.schemata.schema.BrandBuilder.BrandEvent.class, org.schemata.schema.BrandBuilder.BrandEvent.Builder.class);
      }

      // Construct using org.schemata.schema.BrandBuilder.BrandEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (previousBrandStateBuilder_ == null) {
          previousBrandState_ = null;
        } else {
          previousBrandState_ = null;
          previousBrandStateBuilder_ = null;
        }
        if (currentBrandStateBuilder_ == null) {
          currentBrandState_ = null;
        } else {
          currentBrandState_ = null;
          currentBrandStateBuilder_ = null;
        }
        activityType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.schemata.schema.BrandBuilder.internal_static_org_schemata_schema_BrandEvent_descriptor;
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.BrandEvent getDefaultInstanceForType() {
        return org.schemata.schema.BrandBuilder.BrandEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.BrandEvent build() {
        org.schemata.schema.BrandBuilder.BrandEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.schemata.schema.BrandBuilder.BrandEvent buildPartial() {
        org.schemata.schema.BrandBuilder.BrandEvent result = new org.schemata.schema.BrandBuilder.BrandEvent(this);
        if (previousBrandStateBuilder_ == null) {
          result.previousBrandState_ = previousBrandState_;
        } else {
          result.previousBrandState_ = previousBrandStateBuilder_.build();
        }
        if (currentBrandStateBuilder_ == null) {
          result.currentBrandState_ = currentBrandState_;
        } else {
          result.currentBrandState_ = currentBrandStateBuilder_.build();
        }
        result.activityType_ = activityType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.schemata.schema.BrandBuilder.BrandEvent) {
          return mergeFrom((org.schemata.schema.BrandBuilder.BrandEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.schemata.schema.BrandBuilder.BrandEvent other) {
        if (other == org.schemata.schema.BrandBuilder.BrandEvent.getDefaultInstance()) return this;
        if (other.hasPreviousBrandState()) {
          mergePreviousBrandState(other.getPreviousBrandState());
        }
        if (other.hasCurrentBrandState()) {
          mergeCurrentBrandState(other.getCurrentBrandState());
        }
        if (other.activityType_ != 0) {
          setActivityTypeValue(other.getActivityTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.schemata.schema.BrandBuilder.BrandEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.schemata.schema.BrandBuilder.BrandEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.schemata.schema.BrandBuilder.Brand previousBrandState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder> previousBrandStateBuilder_;
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return Whether the previousBrandState field is set.
       */
      public boolean hasPreviousBrandState() {
        return previousBrandStateBuilder_ != null || previousBrandState_ != null;
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The previousBrandState.
       */
      public org.schemata.schema.BrandBuilder.Brand getPreviousBrandState() {
        if (previousBrandStateBuilder_ == null) {
          return previousBrandState_ == null ? org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : previousBrandState_;
        } else {
          return previousBrandStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setPreviousBrandState(org.schemata.schema.BrandBuilder.Brand value) {
        if (previousBrandStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          previousBrandState_ = value;
          onChanged();
        } else {
          previousBrandStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setPreviousBrandState(
          org.schemata.schema.BrandBuilder.Brand.Builder builderForValue) {
        if (previousBrandStateBuilder_ == null) {
          previousBrandState_ = builderForValue.build();
          onChanged();
        } else {
          previousBrandStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder mergePreviousBrandState(org.schemata.schema.BrandBuilder.Brand value) {
        if (previousBrandStateBuilder_ == null) {
          if (previousBrandState_ != null) {
            previousBrandState_ =
              org.schemata.schema.BrandBuilder.Brand.newBuilder(previousBrandState_).mergeFrom(value).buildPartial();
          } else {
            previousBrandState_ = value;
          }
          onChanged();
        } else {
          previousBrandStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder clearPreviousBrandState() {
        if (previousBrandStateBuilder_ == null) {
          previousBrandState_ = null;
          onChanged();
        } else {
          previousBrandState_ = null;
          previousBrandStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.BrandBuilder.Brand.Builder getPreviousBrandStateBuilder() {
        
        onChanged();
        return getPreviousBrandStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.BrandBuilder.BrandOrBuilder getPreviousBrandStateOrBuilder() {
        if (previousBrandStateBuilder_ != null) {
          return previousBrandStateBuilder_.getMessageOrBuilder();
        } else {
          return previousBrandState_ == null ?
              org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : previousBrandState_;
        }
      }
      /**
       * <code>.org.schemata.schema.Brand previous_brand_state = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder> 
          getPreviousBrandStateFieldBuilder() {
        if (previousBrandStateBuilder_ == null) {
          previousBrandStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder>(
                  getPreviousBrandState(),
                  getParentForChildren(),
                  isClean());
          previousBrandState_ = null;
        }
        return previousBrandStateBuilder_;
      }

      private org.schemata.schema.BrandBuilder.Brand currentBrandState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder> currentBrandStateBuilder_;
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return Whether the currentBrandState field is set.
       */
      public boolean hasCurrentBrandState() {
        return currentBrandStateBuilder_ != null || currentBrandState_ != null;
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The currentBrandState.
       */
      public org.schemata.schema.BrandBuilder.Brand getCurrentBrandState() {
        if (currentBrandStateBuilder_ == null) {
          return currentBrandState_ == null ? org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : currentBrandState_;
        } else {
          return currentBrandStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setCurrentBrandState(org.schemata.schema.BrandBuilder.Brand value) {
        if (currentBrandStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          currentBrandState_ = value;
          onChanged();
        } else {
          currentBrandStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setCurrentBrandState(
          org.schemata.schema.BrandBuilder.Brand.Builder builderForValue) {
        if (currentBrandStateBuilder_ == null) {
          currentBrandState_ = builderForValue.build();
          onChanged();
        } else {
          currentBrandStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder mergeCurrentBrandState(org.schemata.schema.BrandBuilder.Brand value) {
        if (currentBrandStateBuilder_ == null) {
          if (currentBrandState_ != null) {
            currentBrandState_ =
              org.schemata.schema.BrandBuilder.Brand.newBuilder(currentBrandState_).mergeFrom(value).buildPartial();
          } else {
            currentBrandState_ = value;
          }
          onChanged();
        } else {
          currentBrandStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder clearCurrentBrandState() {
        if (currentBrandStateBuilder_ == null) {
          currentBrandState_ = null;
          onChanged();
        } else {
          currentBrandState_ = null;
          currentBrandStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.BrandBuilder.Brand.Builder getCurrentBrandStateBuilder() {
        
        onChanged();
        return getCurrentBrandStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.BrandBuilder.BrandOrBuilder getCurrentBrandStateOrBuilder() {
        if (currentBrandStateBuilder_ != null) {
          return currentBrandStateBuilder_.getMessageOrBuilder();
        } else {
          return currentBrandState_ == null ?
              org.schemata.schema.BrandBuilder.Brand.getDefaultInstance() : currentBrandState_;
        }
      }
      /**
       * <code>.org.schemata.schema.Brand current_brand_state = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder> 
          getCurrentBrandStateFieldBuilder() {
        if (currentBrandStateBuilder_ == null) {
          currentBrandStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.schemata.schema.BrandBuilder.Brand, org.schemata.schema.BrandBuilder.Brand.Builder, org.schemata.schema.BrandBuilder.BrandOrBuilder>(
                  getCurrentBrandState(),
                  getParentForChildren(),
                  isClean());
          currentBrandState_ = null;
        }
        return currentBrandStateBuilder_;
      }

      private int activityType_ = 0;
      /**
       * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The enum numeric value on the wire for activityType.
       */
      @java.lang.Override public int getActivityTypeValue() {
        return activityType_;
      }
      /**
       * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The enum numeric value on the wire for activityType to set.
       * @return This builder for chaining.
       */
      public Builder setActivityTypeValue(int value) {
        
        activityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The activityType.
       */
      @java.lang.Override
      public org.schemata.schema.SchemataBuilder.ActivityType getActivityType() {
        @SuppressWarnings("deprecation")
        org.schemata.schema.SchemataBuilder.ActivityType result = org.schemata.schema.SchemataBuilder.ActivityType.valueOf(activityType_);
        return result == null ? org.schemata.schema.SchemataBuilder.ActivityType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The activityType to set.
       * @return This builder for chaining.
       */
      public Builder setActivityType(org.schemata.schema.SchemataBuilder.ActivityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        activityType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.schemata.schema.ActivityType activity_type = 3 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearActivityType() {
        
        activityType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.schemata.schema.BrandEvent)
    }

    // @@protoc_insertion_point(class_scope:org.schemata.schema.BrandEvent)
    private static final org.schemata.schema.BrandBuilder.BrandEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.schemata.schema.BrandBuilder.BrandEvent();
    }

    public static org.schemata.schema.BrandBuilder.BrandEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BrandEvent>
        PARSER = new com.google.protobuf.AbstractParser<BrandEvent>() {
      @java.lang.Override
      public BrandEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BrandEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BrandEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BrandEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.schemata.schema.BrandBuilder.BrandEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_schemata_schema_Brand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_schemata_schema_Brand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_schemata_schema_BrandEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_schemata_schema_BrandEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013brand.proto\022\023org.schemata.schema\032\027sche" +
      "mata_protocol.proto\"\262\003\n\005Brand\0223\n\002id\030\001 \001(" +
      "\005B\'\212\227\"\037\212\265\030\033Unique identifier for Brand\250\227" +
      "\"\001\022\'\n\004name\030\002 \001(\tB\031\212\227\"\025\212\265\030\021Name of the Br" +
      "and\022\224\001\n\tis_active\030\003 \001(\010B\200\001\212\227\"P\212\265\030Ldefine" +
      " the active status of the Brand. `true` " +
      "== active; `false` = inactive`\212\227\"(\222\265\030$sh" +
      "ould refactor to non-binary status:\263\001\212\246\035" +
      ".\212\265\030*This is the description of the Bran" +
      "d table\212\246\035#\222\265\030\037The comment added after t" +
      "hought\212\246\035\030\232\265\030\024db.brand MySQL table\222\246\035\010Pl" +
      "atform\232\246\035\004Core\240\246\035\001\262\246\035\016#team-platform\272\246\035\020" +
      "#alerts-platform\"\355\003\n\nBrandEvent\022z\n\024previ" +
      "ous_brand_state\030\001 \001(\0132\032.org.schemata.sch" +
      "ema.BrandB@\212\227\"<\212\265\0308Previous version of t" +
      "he Brand entity before the mutation\022x\n\023c" +
      "urrent_brand_state\030\002 \001(\0132\032.org.schemata." +
      "schema.BrandB?\212\227\";\212\265\0307Current version of" +
      " the Brand entity before the mutation\022j\n" +
      "\ractivity_type\030\003 \001(\0162!.org.schemata.sche" +
      "ma.ActivityTypeB0\212\227\",\212\265\030(Lifecycle event" +
      " type for the Brand table:}\212\246\0357\212\265\0303This " +
      "is the description of the brand activity" +
      " table\222\246\035\010Platform\232\246\035\004Core\240\246\035\002\300\246\035\001\262\246\035\016#t" +
      "eam-platform\272\246\035\020#alerts-platformB#\n\023org." +
      "schemata.schemaB\014BrandBuilderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.schemata.schema.SchemataBuilder.getDescriptor(),
        });
    internal_static_org_schemata_schema_Brand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_schemata_schema_Brand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_schemata_schema_Brand_descriptor,
        new java.lang.String[] { "Id", "Name", "IsActive", });
    internal_static_org_schemata_schema_BrandEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_schemata_schema_BrandEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_schemata_schema_BrandEvent_descriptor,
        new java.lang.String[] { "PreviousBrandState", "CurrentBrandState", "ActivityType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.schemata.schema.SchemataBuilder.alertChannel);
    registry.add(org.schemata.schema.SchemataBuilder.domain);
    registry.add(org.schemata.schema.SchemataBuilder.eventType);
    registry.add(org.schemata.schema.SchemataBuilder.fieldCore);
    registry.add(org.schemata.schema.SchemataBuilder.isPrimaryKey);
    registry.add(org.schemata.schema.SchemataBuilder.messageCore);
    registry.add(org.schemata.schema.SchemataBuilder.owner);
    registry.add(org.schemata.schema.SchemataBuilder.teamChannel);
    registry.add(org.schemata.schema.SchemataBuilder.type);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.schemata.schema.SchemataBuilder.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
