// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package org.schemata.schema;

public final class ExampleBuilder {
  private ExampleBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DepartmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.schemata.schema.Department)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.schemata.schema.Department}
   */
  public static final class Department extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.schemata.schema.Department)
      DepartmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Department.newBuilder() to construct.
    private Department(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Department() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Department();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Department(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Department_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Department_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.schemata.schema.ExampleBuilder.Department.class, org.schemata.schema.ExampleBuilder.Department.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.schemata.schema.ExampleBuilder.Department)) {
        return super.equals(obj);
      }
      org.schemata.schema.ExampleBuilder.Department other = (org.schemata.schema.ExampleBuilder.Department) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Department parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.schemata.schema.ExampleBuilder.Department prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.schemata.schema.Department}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.schemata.schema.Department)
        org.schemata.schema.ExampleBuilder.DepartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Department_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Department_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.schemata.schema.ExampleBuilder.Department.class, org.schemata.schema.ExampleBuilder.Department.Builder.class);
      }

      // Construct using org.schemata.schema.ExampleBuilder.Department.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Department_descriptor;
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Department getDefaultInstanceForType() {
        return org.schemata.schema.ExampleBuilder.Department.getDefaultInstance();
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Department build() {
        org.schemata.schema.ExampleBuilder.Department result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Department buildPartial() {
        org.schemata.schema.ExampleBuilder.Department result = new org.schemata.schema.ExampleBuilder.Department(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.schemata.schema.ExampleBuilder.Department) {
          return mergeFrom((org.schemata.schema.ExampleBuilder.Department)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.schemata.schema.ExampleBuilder.Department other) {
        if (other == org.schemata.schema.ExampleBuilder.Department.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.schemata.schema.ExampleBuilder.Department parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.schemata.schema.ExampleBuilder.Department) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.schemata.schema.Department)
    }

    // @@protoc_insertion_point(class_scope:org.schemata.schema.Department)
    private static final org.schemata.schema.ExampleBuilder.Department DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.schemata.schema.ExampleBuilder.Department();
    }

    public static org.schemata.schema.ExampleBuilder.Department getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Department>
        PARSER = new com.google.protobuf.AbstractParser<Department>() {
      @java.lang.Override
      public Department parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Department(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Department> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Department> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.schemata.schema.ExampleBuilder.Department getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.schemata.schema.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the dept field is set.
     */
    boolean hasDept();
    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The dept.
     */
    org.schemata.schema.ExampleBuilder.Department getDept();
    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    org.schemata.schema.ExampleBuilder.DepartmentOrBuilder getDeptOrBuilder();
  }
  /**
   * Protobuf type {@code org.schemata.schema.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.schemata.schema.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              org.schemata.schema.ExampleBuilder.Department.Builder subBuilder = null;
              if (dept_ != null) {
                subBuilder = dept_.toBuilder();
              }
              dept_ = input.readMessage(org.schemata.schema.ExampleBuilder.Department.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dept_);
                dept_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.schemata.schema.ExampleBuilder.Person.class, org.schemata.schema.ExampleBuilder.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPT_FIELD_NUMBER = 4;
    private org.schemata.schema.ExampleBuilder.Department dept_;
    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return Whether the dept field is set.
     */
    @java.lang.Override
    public boolean hasDept() {
      return dept_ != null;
    }
    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     * @return The dept.
     */
    @java.lang.Override
    public org.schemata.schema.ExampleBuilder.Department getDept() {
      return dept_ == null ? org.schemata.schema.ExampleBuilder.Department.getDefaultInstance() : dept_;
    }
    /**
     * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
     */
    @java.lang.Override
    public org.schemata.schema.ExampleBuilder.DepartmentOrBuilder getDeptOrBuilder() {
      return getDept();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (dept_ != null) {
        output.writeMessage(4, getDept());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (dept_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDept());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.schemata.schema.ExampleBuilder.Person)) {
        return super.equals(obj);
      }
      org.schemata.schema.ExampleBuilder.Person other = (org.schemata.schema.ExampleBuilder.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (hasDept() != other.hasDept()) return false;
      if (hasDept()) {
        if (!getDept()
            .equals(other.getDept())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasDept()) {
        hash = (37 * hash) + DEPT_FIELD_NUMBER;
        hash = (53 * hash) + getDept().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.ExampleBuilder.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.schemata.schema.ExampleBuilder.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.schemata.schema.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.schemata.schema.Person)
        org.schemata.schema.ExampleBuilder.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.schemata.schema.ExampleBuilder.Person.class, org.schemata.schema.ExampleBuilder.Person.Builder.class);
      }

      // Construct using org.schemata.schema.ExampleBuilder.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        email_ = "";

        if (deptBuilder_ == null) {
          dept_ = null;
        } else {
          dept_ = null;
          deptBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.schemata.schema.ExampleBuilder.internal_static_org_schemata_schema_Person_descriptor;
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Person getDefaultInstanceForType() {
        return org.schemata.schema.ExampleBuilder.Person.getDefaultInstance();
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Person build() {
        org.schemata.schema.ExampleBuilder.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.schemata.schema.ExampleBuilder.Person buildPartial() {
        org.schemata.schema.ExampleBuilder.Person result = new org.schemata.schema.ExampleBuilder.Person(this);
        result.name_ = name_;
        result.id_ = id_;
        result.email_ = email_;
        if (deptBuilder_ == null) {
          result.dept_ = dept_;
        } else {
          result.dept_ = deptBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.schemata.schema.ExampleBuilder.Person) {
          return mergeFrom((org.schemata.schema.ExampleBuilder.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.schemata.schema.ExampleBuilder.Person other) {
        if (other == org.schemata.schema.ExampleBuilder.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasDept()) {
          mergeDept(other.getDept());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.schemata.schema.ExampleBuilder.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.schemata.schema.ExampleBuilder.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3 [(.org.schemata.schema.classification_level) = "HIGH", (.org.schemata.schema.field_core) = { ... }</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private org.schemata.schema.ExampleBuilder.Department dept_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.ExampleBuilder.Department, org.schemata.schema.ExampleBuilder.Department.Builder, org.schemata.schema.ExampleBuilder.DepartmentOrBuilder> deptBuilder_;
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return Whether the dept field is set.
       */
      public boolean hasDept() {
        return deptBuilder_ != null || dept_ != null;
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       * @return The dept.
       */
      public org.schemata.schema.ExampleBuilder.Department getDept() {
        if (deptBuilder_ == null) {
          return dept_ == null ? org.schemata.schema.ExampleBuilder.Department.getDefaultInstance() : dept_;
        } else {
          return deptBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setDept(org.schemata.schema.ExampleBuilder.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dept_ = value;
          onChanged();
        } else {
          deptBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder setDept(
          org.schemata.schema.ExampleBuilder.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          dept_ = builderForValue.build();
          onChanged();
        } else {
          deptBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder mergeDept(org.schemata.schema.ExampleBuilder.Department value) {
        if (deptBuilder_ == null) {
          if (dept_ != null) {
            dept_ =
              org.schemata.schema.ExampleBuilder.Department.newBuilder(dept_).mergeFrom(value).buildPartial();
          } else {
            dept_ = value;
          }
          onChanged();
        } else {
          deptBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public Builder clearDept() {
        if (deptBuilder_ == null) {
          dept_ = null;
          onChanged();
        } else {
          dept_ = null;
          deptBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.ExampleBuilder.Department.Builder getDeptBuilder() {
        
        onChanged();
        return getDeptFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      public org.schemata.schema.ExampleBuilder.DepartmentOrBuilder getDeptOrBuilder() {
        if (deptBuilder_ != null) {
          return deptBuilder_.getMessageOrBuilder();
        } else {
          return dept_ == null ?
              org.schemata.schema.ExampleBuilder.Department.getDefaultInstance() : dept_;
        }
      }
      /**
       * <code>.org.schemata.schema.Department dept = 4 [(.org.schemata.schema.field_core) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.schemata.schema.ExampleBuilder.Department, org.schemata.schema.ExampleBuilder.Department.Builder, org.schemata.schema.ExampleBuilder.DepartmentOrBuilder> 
          getDeptFieldBuilder() {
        if (deptBuilder_ == null) {
          deptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.schemata.schema.ExampleBuilder.Department, org.schemata.schema.ExampleBuilder.Department.Builder, org.schemata.schema.ExampleBuilder.DepartmentOrBuilder>(
                  getDept(),
                  getParentForChildren(),
                  isClean());
          dept_ = null;
        }
        return deptBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.schemata.schema.Person)
    }

    // @@protoc_insertion_point(class_scope:org.schemata.schema.Person)
    private static final org.schemata.schema.ExampleBuilder.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.schemata.schema.ExampleBuilder.Person();
    }

    public static org.schemata.schema.ExampleBuilder.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.schemata.schema.ExampleBuilder.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_schemata_schema_Department_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_schemata_schema_Department_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_schemata_schema_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_schemata_schema_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\023org.schemata.schema\032 go" +
      "ogle/protobuf/descriptor.proto\032\027schemata" +
      "_protocol.proto\"&\n\nDepartment\022\n\n\002id\030\001 \001(" +
      "\005\022\014\n\004name\030\002 \001(\t\"\364\002\n\006Person\022!\n\004name\030\001 \001(\t" +
      "B\023\212\227\"\017\212\265\030\013person name\022<\n\002id\030\002 \001(\005B0\212\227\"(\212" +
      "\265\030$unique identifier for a given person\250" +
      "\227\"\001\022B\n\005email\030\003 \001(\tB3\212\227\"\032\212\265\030\026official ema" +
      "il address\220\227\"\001\332\265\003\004HIGH\242\227\"\005email\022T\n\004dept\030" +
      "\004 \001(\0132\037.org.schemata.schema.DepartmentB%" +
      "\212\227\"!\212\265\030\035department name of the person:o\212" +
      "\246\035.\212\265\030*This is the description of the us" +
      "ers table\212\246\035#\222\265\030\037The comment added after" +
      " thought\222\246\035\006Growth\232\246\035\004Core\240\246\035\001B%\n\023org.sc" +
      "hemata.schemaB\016ExampleBuilderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          org.schemata.schema.SchemataBuilder.getDescriptor(),
        });
    internal_static_org_schemata_schema_Department_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_schemata_schema_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_schemata_schema_Department_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_org_schemata_schema_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_schemata_schema_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_schemata_schema_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Dept", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.schemata.schema.SchemataBuilder.classificationLevel);
    registry.add(org.schemata.schema.SchemataBuilder.domain);
    registry.add(org.schemata.schema.SchemataBuilder.fieldCore);
    registry.add(org.schemata.schema.SchemataBuilder.isClassified);
    registry.add(org.schemata.schema.SchemataBuilder.isPrimaryKey);
    registry.add(org.schemata.schema.SchemataBuilder.messageCore);
    registry.add(org.schemata.schema.SchemataBuilder.owner);
    registry.add(org.schemata.schema.SchemataBuilder.productType);
    registry.add(org.schemata.schema.SchemataBuilder.type);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
    org.schemata.schema.SchemataBuilder.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
