// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schemata_protocol.proto

package org.schemata.schema;

public final class SchemataBuilder {
  private SchemataBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.schemata.schema.SchemataBuilder.messageCore);
    registry.add(org.schemata.schema.SchemataBuilder.owner);
    registry.add(org.schemata.schema.SchemataBuilder.domain);
    registry.add(org.schemata.schema.SchemataBuilder.type);
    registry.add(org.schemata.schema.SchemataBuilder.status);
    registry.add(org.schemata.schema.SchemataBuilder.teamChannel);
    registry.add(org.schemata.schema.SchemataBuilder.alertChannel);
    registry.add(org.schemata.schema.SchemataBuilder.eventType);
    registry.add(org.schemata.schema.SchemataBuilder.complianceOwner);
    registry.add(org.schemata.schema.SchemataBuilder.complianceChannel);
    registry.add(org.schemata.schema.SchemataBuilder.fieldCore);
    registry.add(org.schemata.schema.SchemataBuilder.isClassified);
    registry.add(org.schemata.schema.SchemataBuilder.classificationLevel);
    registry.add(org.schemata.schema.SchemataBuilder.productType);
    registry.add(org.schemata.schema.SchemataBuilder.isPrimaryKey);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * MessageType captures the type of the stream. There are two types of stream.
   * </pre>
   *
   * Protobuf enum {@code org.schemata.schema.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * This is an invalid state. If the entity defined as unknown the validator should throw an exception.
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     *Entity streams can be mutated in the downstream services. Entity streams often used to represent the current
     *state of the entity. In the classical DW concepts Entities typically represents the dimensions.
     * Entity must have a primary key field.
     * </pre>
     *
     * <code>ENTITY = 1;</code>
     */
    ENTITY(1),
    /**
     * <pre>
     * Event streams are typically immutable in nature. Event streams often used to represent the state change of an Entity.
     * In the classical DW concepts Event streams represents the facts. Event streams will not have a primary key field.
     * </pre>
     *
     * <code>EVENT = 2;</code>
     */
    EVENT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * This is an invalid state. If the entity defined as unknown the validator should throw an exception.
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     *Entity streams can be mutated in the downstream services. Entity streams often used to represent the current
     *state of the entity. In the classical DW concepts Entities typically represents the dimensions.
     * Entity must have a primary key field.
     * </pre>
     *
     * <code>ENTITY = 1;</code>
     */
    public static final int ENTITY_VALUE = 1;
    /**
     * <pre>
     * Event streams are typically immutable in nature. Event streams often used to represent the state change of an Entity.
     * In the classical DW concepts Event streams represents the facts. Event streams will not have a primary key field.
     * </pre>
     *
     * <code>EVENT = 2;</code>
     */
    public static final int EVENT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ENTITY;
        case 2: return EVENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.schemata.schema.SchemataBuilder.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.schemata.schema.Type)
  }

  /**
   * Protobuf enum {@code org.schemata.schema.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Invalid Event Type. If the message type is event, set it either LIFECYCLE or ACTIVITY or AGGREGATED
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <pre>
     * LIFECYCLE event captures the state changes of an Entity. (e.g) User created, User deleted et al.
     * </pre>
     *
     * <code>LIFECYCLE = 1;</code>
     */
    LIFECYCLE(1),
    /**
     * <pre>
     * ACTIVITY event captures the events that resulted from one Entity changing the state of another Entity.
     * (e.g.) User A purchases Product B. The ACTIVITY event is often the result of a business transaction.
     * </pre>
     *
     * <code>ACTIVITY = 2;</code>
     */
    ACTIVITY(2),
    /**
     * <pre>
     * AGGREGATED event captures the computed metrics over a specified window of time. (e.g) Number of views by a User for a Product.
     * </pre>
     *
     * <code>AGGREGATED = 3;</code>
     */
    AGGREGATED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Invalid Event Type. If the message type is event, set it either LIFECYCLE or ACTIVITY or AGGREGATED
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <pre>
     * LIFECYCLE event captures the state changes of an Entity. (e.g) User created, User deleted et al.
     * </pre>
     *
     * <code>LIFECYCLE = 1;</code>
     */
    public static final int LIFECYCLE_VALUE = 1;
    /**
     * <pre>
     * ACTIVITY event captures the events that resulted from one Entity changing the state of another Entity.
     * (e.g.) User A purchases Product B. The ACTIVITY event is often the result of a business transaction.
     * </pre>
     *
     * <code>ACTIVITY = 2;</code>
     */
    public static final int ACTIVITY_VALUE = 2;
    /**
     * <pre>
     * AGGREGATED event captures the computed metrics over a specified window of time. (e.g) Number of views by a User for a Product.
     * </pre>
     *
     * <code>AGGREGATED = 3;</code>
     */
    public static final int AGGREGATED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return LIFECYCLE;
        case 2: return ACTIVITY;
        case 3: return AGGREGATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.schemata.schema.SchemataBuilder.getDescriptor().getEnumTypes().get(1);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.schemata.schema.EventType)
  }

  /**
   * Protobuf enum {@code org.schemata.schema.ActivityType}
   */
  public enum ActivityType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATED = 0;</code>
     */
    CREATED(0),
    /**
     * <code>DELETED = 1;</code>
     */
    DELETED(1),
    /**
     * <code>UPDATED = 2;</code>
     */
    UPDATED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATED = 0;</code>
     */
    public static final int CREATED_VALUE = 0;
    /**
     * <code>DELETED = 1;</code>
     */
    public static final int DELETED_VALUE = 1;
    /**
     * <code>UPDATED = 2;</code>
     */
    public static final int UPDATED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActivityType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActivityType forNumber(int value) {
      switch (value) {
        case 0: return CREATED;
        case 1: return DELETED;
        case 2: return UPDATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActivityType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActivityType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActivityType>() {
            public ActivityType findValueByNumber(int number) {
              return ActivityType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.schemata.schema.SchemataBuilder.getDescriptor().getEnumTypes().get(2);
    }

    private static final ActivityType[] VALUES = values();

    public static ActivityType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActivityType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.schemata.schema.ActivityType)
  }

  /**
   * Protobuf enum {@code org.schemata.schema.TimeUnit}
   */
  public enum TimeUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SECONDS = 0;</code>
     */
    SECONDS(0),
    /**
     * <code>MINUTES = 1;</code>
     */
    MINUTES(1),
    /**
     * <code>HOURS = 2;</code>
     */
    HOURS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SECONDS = 0;</code>
     */
    public static final int SECONDS_VALUE = 0;
    /**
     * <code>MINUTES = 1;</code>
     */
    public static final int MINUTES_VALUE = 1;
    /**
     * <code>HOURS = 2;</code>
     */
    public static final int HOURS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TimeUnit valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TimeUnit forNumber(int value) {
      switch (value) {
        case 0: return SECONDS;
        case 1: return MINUTES;
        case 2: return HOURS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TimeUnit> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TimeUnit>() {
            public TimeUnit findValueByNumber(int number) {
              return TimeUnit.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.schemata.schema.SchemataBuilder.getDescriptor().getEnumTypes().get(3);
    }

    private static final TimeUnit[] VALUES = values();

    public static TimeUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TimeUnit(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.schemata.schema.TimeUnit)
  }

  public interface CoreMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.schemata.schema.CoreMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return Whether the comment field is set.
     */
    boolean hasComment();
    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return The comment.
     */
    java.lang.String getComment();
    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return Whether the seeAlso field is set.
     */
    boolean hasSeeAlso();
    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return The seeAlso.
     */
    java.lang.String getSeeAlso();
    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return The bytes for seeAlso.
     */
    com.google.protobuf.ByteString
        getSeeAlsoBytes();

    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return Whether the reference field is set.
     */
    boolean hasReference();
    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return The reference.
     */
    java.lang.String getReference();
    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return The bytes for reference.
     */
    com.google.protobuf.ByteString
        getReferenceBytes();
  }
  /**
   * <pre>
   * CoreMetadata is the set of attribute apply to both the Message &amp; Field
   * </pre>
   *
   * Protobuf type {@code org.schemata.schema.CoreMetadata}
   */
  public static final class CoreMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.schemata.schema.CoreMetadata)
      CoreMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CoreMetadata.newBuilder() to construct.
    private CoreMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CoreMetadata() {
      description_ = "";
      comment_ = "";
      seeAlso_ = "";
      reference_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CoreMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CoreMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 400010: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              description_ = s;
              break;
            }
            case 400018: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              comment_ = s;
              break;
            }
            case 400026: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              seeAlso_ = s;
              break;
            }
            case 400034: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              reference_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.schemata.schema.SchemataBuilder.internal_static_org_schemata_schema_CoreMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.schemata.schema.SchemataBuilder.internal_static_org_schemata_schema_CoreMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.schemata.schema.SchemataBuilder.CoreMetadata.class, org.schemata.schema.SchemataBuilder.CoreMetadata.Builder.class);
    }

    private int bitField0_;
    public static final int DESCRIPTION_FIELD_NUMBER = 50001;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Mandatory Metadata: description of the entity
     * </pre>
     *
     * <code>optional string description = 50001;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENT_FIELD_NUMBER = 50002;
    private volatile java.lang.Object comment_;
    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return Whether the comment field is set.
     */
    @java.lang.Override
    public boolean hasComment() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return The comment.
     */
    @java.lang.Override
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional Metadata: additional comments about the entity
     * </pre>
     *
     * <code>optional string comment = 50002;</code>
     * @return The bytes for comment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEE_ALSO_FIELD_NUMBER = 50003;
    private volatile java.lang.Object seeAlso_;
    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return Whether the seeAlso field is set.
     */
    @java.lang.Override
    public boolean hasSeeAlso() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return The seeAlso.
     */
    @java.lang.Override
    public java.lang.String getSeeAlso() {
      java.lang.Object ref = seeAlso_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seeAlso_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
     * </pre>
     *
     * <code>optional string see_also = 50003;</code>
     * @return The bytes for seeAlso.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSeeAlsoBytes() {
      java.lang.Object ref = seeAlso_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seeAlso_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCE_FIELD_NUMBER = 50004;
    private volatile java.lang.Object reference_;
    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return Whether the reference field is set.
     */
    @java.lang.Override
    public boolean hasReference() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return The reference.
     */
    @java.lang.Override
    public java.lang.String getReference() {
      java.lang.Object ref = reference_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reference_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional Metadata: Additional link reference for further reading.
     * It could be a confluent page, An ADR or RFC or a Slack message link.
     * </pre>
     *
     * <code>optional string reference = 50004;</code>
     * @return The bytes for reference.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReferenceBytes() {
      java.lang.Object ref = reference_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 50001, description_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 50002, comment_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 50003, seeAlso_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 50004, reference_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(50001, description_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(50002, comment_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(50003, seeAlso_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(50004, reference_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.schemata.schema.SchemataBuilder.CoreMetadata)) {
        return super.equals(obj);
      }
      org.schemata.schema.SchemataBuilder.CoreMetadata other = (org.schemata.schema.SchemataBuilder.CoreMetadata) obj;

      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (hasComment() != other.hasComment()) return false;
      if (hasComment()) {
        if (!getComment()
            .equals(other.getComment())) return false;
      }
      if (hasSeeAlso() != other.hasSeeAlso()) return false;
      if (hasSeeAlso()) {
        if (!getSeeAlso()
            .equals(other.getSeeAlso())) return false;
      }
      if (hasReference() != other.hasReference()) return false;
      if (hasReference()) {
        if (!getReference()
            .equals(other.getReference())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      if (hasComment()) {
        hash = (37 * hash) + COMMENT_FIELD_NUMBER;
        hash = (53 * hash) + getComment().hashCode();
      }
      if (hasSeeAlso()) {
        hash = (37 * hash) + SEE_ALSO_FIELD_NUMBER;
        hash = (53 * hash) + getSeeAlso().hashCode();
      }
      if (hasReference()) {
        hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getReference().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.schemata.schema.SchemataBuilder.CoreMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.schemata.schema.SchemataBuilder.CoreMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CoreMetadata is the set of attribute apply to both the Message &amp; Field
     * </pre>
     *
     * Protobuf type {@code org.schemata.schema.CoreMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.schemata.schema.CoreMetadata)
        org.schemata.schema.SchemataBuilder.CoreMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.schemata.schema.SchemataBuilder.internal_static_org_schemata_schema_CoreMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.schemata.schema.SchemataBuilder.internal_static_org_schemata_schema_CoreMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.schemata.schema.SchemataBuilder.CoreMetadata.class, org.schemata.schema.SchemataBuilder.CoreMetadata.Builder.class);
      }

      // Construct using org.schemata.schema.SchemataBuilder.CoreMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seeAlso_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        reference_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.schemata.schema.SchemataBuilder.internal_static_org_schemata_schema_CoreMetadata_descriptor;
      }

      @java.lang.Override
      public org.schemata.schema.SchemataBuilder.CoreMetadata getDefaultInstanceForType() {
        return org.schemata.schema.SchemataBuilder.CoreMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public org.schemata.schema.SchemataBuilder.CoreMetadata build() {
        org.schemata.schema.SchemataBuilder.CoreMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.schemata.schema.SchemataBuilder.CoreMetadata buildPartial() {
        org.schemata.schema.SchemataBuilder.CoreMetadata result = new org.schemata.schema.SchemataBuilder.CoreMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.comment_ = comment_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seeAlso_ = seeAlso_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reference_ = reference_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.schemata.schema.SchemataBuilder.CoreMetadata) {
          return mergeFrom((org.schemata.schema.SchemataBuilder.CoreMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.schemata.schema.SchemataBuilder.CoreMetadata other) {
        if (other == org.schemata.schema.SchemataBuilder.CoreMetadata.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          bitField0_ |= 0x00000001;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasComment()) {
          bitField0_ |= 0x00000002;
          comment_ = other.comment_;
          onChanged();
        }
        if (other.hasSeeAlso()) {
          bitField0_ |= 0x00000004;
          seeAlso_ = other.seeAlso_;
          onChanged();
        }
        if (other.hasReference()) {
          bitField0_ |= 0x00000008;
          reference_ = other.reference_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.schemata.schema.SchemataBuilder.CoreMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.schemata.schema.SchemataBuilder.CoreMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Mandatory Metadata: description of the entity
       * </pre>
       *
       * <code>optional string description = 50001;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @return Whether the comment field is set.
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @return The comment.
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @return The bytes for comment.
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @param value The comment to set.
       * @return This builder for chaining.
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @return This builder for chaining.
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000002);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: additional comments about the entity
       * </pre>
       *
       * <code>optional string comment = 50002;</code>
       * @param value The bytes for comment to set.
       * @return This builder for chaining.
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        comment_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object seeAlso_ = "";
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @return Whether the seeAlso field is set.
       */
      public boolean hasSeeAlso() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @return The seeAlso.
       */
      public java.lang.String getSeeAlso() {
        java.lang.Object ref = seeAlso_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seeAlso_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @return The bytes for seeAlso.
       */
      public com.google.protobuf.ByteString
          getSeeAlsoBytes() {
        java.lang.Object ref = seeAlso_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seeAlso_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @param value The seeAlso to set.
       * @return This builder for chaining.
       */
      public Builder setSeeAlso(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        seeAlso_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeeAlso() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seeAlso_ = getDefaultInstance().getSeeAlso();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: Any related entity that has "hierarchy" or "has a"  relationships.
       * </pre>
       *
       * <code>optional string see_also = 50003;</code>
       * @param value The bytes for seeAlso to set.
       * @return This builder for chaining.
       */
      public Builder setSeeAlsoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        seeAlso_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reference_ = "";
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @return Whether the reference field is set.
       */
      public boolean hasReference() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @return The reference.
       */
      public java.lang.String getReference() {
        java.lang.Object ref = reference_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reference_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @return The bytes for reference.
       */
      public com.google.protobuf.ByteString
          getReferenceBytes() {
        java.lang.Object ref = reference_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reference_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @param value The reference to set.
       * @return This builder for chaining.
       */
      public Builder setReference(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        reference_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @return This builder for chaining.
       */
      public Builder clearReference() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reference_ = getDefaultInstance().getReference();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional Metadata: Additional link reference for further reading.
       * It could be a confluent page, An ADR or RFC or a Slack message link.
       * </pre>
       *
       * <code>optional string reference = 50004;</code>
       * @param value The bytes for reference to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        reference_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.schemata.schema.CoreMetadata)
    }

    // @@protoc_insertion_point(class_scope:org.schemata.schema.CoreMetadata)
    private static final org.schemata.schema.SchemataBuilder.CoreMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.schemata.schema.SchemataBuilder.CoreMetadata();
    }

    public static org.schemata.schema.SchemataBuilder.CoreMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoreMetadata>
        PARSER = new com.google.protobuf.AbstractParser<CoreMetadata>() {
      @java.lang.Override
      public CoreMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoreMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CoreMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoreMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.schemata.schema.SchemataBuilder.CoreMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MESSAGE_CORE_FIELD_NUMBER = 60001;
  /**
   * <pre>
   * message.description is a Mandatory Metadata
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      org.schemata.schema.SchemataBuilder.CoreMetadata> messageCore = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.schemata.schema.SchemataBuilder.CoreMetadata.class,
        org.schemata.schema.SchemataBuilder.CoreMetadata.getDefaultInstance());
  public static final int OWNER_FIELD_NUMBER = 60002;
  /**
   * <pre>
   * Mandatory Metadata: owner of the entity. Usually it is the team name.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> owner = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DOMAIN_FIELD_NUMBER = 60003;
  /**
   * <pre>
   * Mandatory Metadata: domain = 'core' indicates the entity is common across all the domains.
   * Other possible domains are `sales`, `marketing`, `product` etc
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> domain = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TYPE_FIELD_NUMBER = 60004;
  /**
   * <pre>
   * Mandatory Metadata: define the type of the message.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      org.schemata.schema.SchemataBuilder.Type> type = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.schemata.schema.SchemataBuilder.Type.class,
        null);
  public static final int STATUS_FIELD_NUMBER = 60005;
  /**
   * <pre>
   * Status of the entity. You can have `testing`, `production` or `staging` depends on the lifecycle of schema definition.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> status = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TEAM_CHANNEL_FIELD_NUMBER = 60006;
  /**
   * <pre>
   * Slack or Teams channel name to communicate with the team which owns ths entity
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> teamChannel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ALERT_CHANNEL_FIELD_NUMBER = 60007;
  /**
   * <pre>
   * Slack or Teams channel name to alert for any validation errors.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> alertChannel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int EVENT_TYPE_FIELD_NUMBER = 60008;
  /**
   * <pre>
   * Type of the event. Set if the Type = 'EVENT'
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      org.schemata.schema.SchemataBuilder.EventType> eventType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.schemata.schema.SchemataBuilder.EventType.class,
        null);
  public static final int COMPLIANCE_OWNER_FIELD_NUMBER = 60009;
  /**
   * <pre>
   * Compliance Owner approves which team should have access to this Schema.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> complianceOwner = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int COMPLIANCE_CHANNEL_FIELD_NUMBER = 600010;
  /**
   * <pre>
   * Compliance Owner Slack/ Teams Channel name
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> complianceChannel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FIELD_CORE_FIELD_NUMBER = 70001;
  /**
   * <pre>
   * message.description is a Mandatory Metadata
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.schemata.schema.SchemataBuilder.CoreMetadata> fieldCore = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.schemata.schema.SchemataBuilder.CoreMetadata.class,
        org.schemata.schema.SchemataBuilder.CoreMetadata.getDefaultInstance());
  public static final int IS_CLASSIFIED_FIELD_NUMBER = 70002;
  /**
   * <pre>
   * Set true if the field contains classified data (Optional).
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> isClassified = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CLASSIFICATION_LEVEL_FIELD_NUMBER = 7003;
  /**
   * <pre>
   * Set the classification level if is_classified is true (This is Mandatory if is_classified set to true)
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> classificationLevel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PRODUCT_TYPE_FIELD_NUMBER = 70004;
  /**
   * <pre>
   * Specify the product type. product_type is an useful annotation to represent a field in a business perspective.
   * (e.g) user_id can be an INT field, but in the system design it could represent External Users rather than internal users.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> productType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int IS_PRIMARY_KEY_FIELD_NUMBER = 70005;
  /**
   * <pre>
   * Set true if the field is a primary key. This must be true if the Schema type is Entity
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> isPrimaryKey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_schemata_schema_CoreMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_schemata_schema_CoreMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027schemata_protocol.proto\022\023org.schemata." +
      "schema\032 google/protobuf/descriptor.proto" +
      "\"\254\001\n\014CoreMetadata\022\032\n\013description\030\321\206\003 \001(\t" +
      "H\000\210\001\001\022\026\n\007comment\030\322\206\003 \001(\tH\001\210\001\001\022\027\n\010see_als" +
      "o\030\323\206\003 \001(\tH\002\210\001\001\022\030\n\treference\030\324\206\003 \001(\tH\003\210\001\001" +
      "B\016\n\014_descriptionB\n\n\010_commentB\013\n\t_see_als" +
      "oB\014\n\n_reference**\n\004Type\022\013\n\007UNKNOWN\020\000\022\n\n\006" +
      "ENTITY\020\001\022\t\n\005EVENT\020\002*B\n\tEventType\022\010\n\004NONE" +
      "\020\000\022\r\n\tLIFECYCLE\020\001\022\014\n\010ACTIVITY\020\002\022\016\n\nAGGRE" +
      "GATED\020\003*5\n\014ActivityType\022\013\n\007CREATED\020\000\022\013\n\007" +
      "DELETED\020\001\022\013\n\007UPDATED\020\002*/\n\010TimeUnit\022\013\n\007SE" +
      "CONDS\020\000\022\013\n\007MINUTES\020\001\022\t\n\005HOURS\020\002:Z\n\014messa" +
      "ge_core\022\037.google.protobuf.MessageOptions" +
      "\030\341\324\003 \001(\0132!.org.schemata.schema.CoreMetad" +
      "ata:0\n\005owner\022\037.google.protobuf.MessageOp" +
      "tions\030\342\324\003 \001(\t:1\n\006domain\022\037.google.protobu" +
      "f.MessageOptions\030\343\324\003 \001(\t:J\n\004type\022\037.googl" +
      "e.protobuf.MessageOptions\030\344\324\003 \001(\0162\031.org." +
      "schemata.schema.Type:1\n\006status\022\037.google." +
      "protobuf.MessageOptions\030\345\324\003 \001(\t:7\n\014team_" +
      "channel\022\037.google.protobuf.MessageOptions" +
      "\030\346\324\003 \001(\t:8\n\ralert_channel\022\037.google.proto" +
      "buf.MessageOptions\030\347\324\003 \001(\t:U\n\nevent_type" +
      "\022\037.google.protobuf.MessageOptions\030\350\324\003 \001(" +
      "\0162\036.org.schemata.schema.EventType:;\n\020com" +
      "pliance_owner\022\037.google.protobuf.MessageO" +
      "ptions\030\351\324\003 \001(\t:=\n\022compliance_channel\022\037.g" +
      "oogle.protobuf.MessageOptions\030\312\317$ \001(\t:V\n" +
      "\nfield_core\022\035.google.protobuf.FieldOptio" +
      "ns\030\361\242\004 \001(\0132!.org.schemata.schema.CoreMet" +
      "adata:6\n\ris_classified\022\035.google.protobuf" +
      ".FieldOptions\030\362\242\004 \001(\010:<\n\024classification_" +
      "level\022\035.google.protobuf.FieldOptions\030\3336 " +
      "\001(\t:5\n\014product_type\022\035.google.protobuf.Fi" +
      "eldOptions\030\364\242\004 \001(\t:7\n\016is_primary_key\022\035.g" +
      "oogle.protobuf.FieldOptions\030\365\242\004 \001(\010B&\n\023o" +
      "rg.schemata.schemaB\017SchemataBuilderb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_org_schemata_schema_CoreMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_schemata_schema_CoreMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_schemata_schema_CoreMetadata_descriptor,
        new java.lang.String[] { "Description", "Comment", "SeeAlso", "Reference", "Description", "Comment", "SeeAlso", "Reference", });
    messageCore.internalInit(descriptor.getExtensions().get(0));
    owner.internalInit(descriptor.getExtensions().get(1));
    domain.internalInit(descriptor.getExtensions().get(2));
    type.internalInit(descriptor.getExtensions().get(3));
    status.internalInit(descriptor.getExtensions().get(4));
    teamChannel.internalInit(descriptor.getExtensions().get(5));
    alertChannel.internalInit(descriptor.getExtensions().get(6));
    eventType.internalInit(descriptor.getExtensions().get(7));
    complianceOwner.internalInit(descriptor.getExtensions().get(8));
    complianceChannel.internalInit(descriptor.getExtensions().get(9));
    fieldCore.internalInit(descriptor.getExtensions().get(10));
    isClassified.internalInit(descriptor.getExtensions().get(11));
    classificationLevel.internalInit(descriptor.getExtensions().get(12));
    productType.internalInit(descriptor.getExtensions().get(13));
    isPrimaryKey.internalInit(descriptor.getExtensions().get(14));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
