name: ProtoBuf Backward Compatibility check

on:
  pull_request:

jobs:
  clone_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Install protoc using apt-get
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version

    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        path: base-branch
        
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run compile command on PR and base branches
      run: |
        echo "Running compile command on PR branch:"
        protoc  --proto_path=src/opencontract/v1/org --proto_path=src/main/resources/schema --descriptor_set_out=model.desc --include_imports --include_source_info ./src/main/resources/**/*.proto
        echo "Running compile command on base branch:"
        cd base-branch
        protoc  --proto_path=src/opencontract/v1/org --proto_path=src/main/resources/schema --descriptor_set_out=model.desc --include_imports --include_source_info ./src/main/resources/**/*.proto
        cd ..
    
    - name: Download Schemata jar
      run: |
        curl -L -o schemata.jar https://github.com/ananthdurai/schemata/releases/download/v0.2/schemata-1.0.jar        
        
    - name: Run ProtoBuf Backward compatibility changes
      run: |
        java -jar schemata.jar isBackwardCompatible -s model.desc -b base-branch/model.desc -p protobuf
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "ProtoBuf Backward compatibility check passed"
        else
          echo "ProtoBuf Backward compatibility check failed"
          java -jar schemata.jar compatibilitySummary -s model.desc -b base-branch/model.desc -p protobuf
          exit 1
        fi
    
